name: Bug report
description: File a bug
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you saw.
      placeholder: Steps to reproduce...
    validations:
      required: true