name: pre-commit

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry==1.8.3
      - name: Install deps
        run: |
          poetry env use 3.12
          poetry install
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --show-diff-on-failure --all-files